version: "3.9"

services:
  app:
    build:
      context: .
    container_name: golang-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ArnavJain
      DB_PASSWORD: admin
      DB_NAME: CSV_db

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ArnavJain
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: CSV_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ArnavJain -d CSV_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: jainarnav98@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      GUNICORN_TIMEOUT: "90"
    ports:
      - "5050:80"

volumes:
  postgres-data:
